version: '3'
services:
  db:
    container_name: mydb
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - 5566:5432
    restart: always
  auth:
    container_name: my-group-auth
    image: fusionauth/fusionauth-app:latest
    ports:
      - 9011:9011
    environment:
      - DATABASE_URL=jdbc:postgresql://db:5432/postgres
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=${DB_PASSWORD}
    restart: always