version: '3'
services:
  db:
    container_name: mydb
    image: postgres:latest
    environment:
      - POSTGRES_USERNAME=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - ${POSTGRES_PORTS}
    restart: always
    
  auth:
    container_name: my-group-auth
    image: fusionauth/fusionauth-app:latest
    ports:
      - ${FUSI_PORTS}
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DB_PASSWORD}
    restart: always